/*
Copyright (c) 2017, Nordic Semiconductor ASA

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form, except as embedded into a Nordic
   Semiconductor ASA integrated circuit in a product or a software update for
   such product, must reproduce the above copyright notice, this list of
   conditions and the following disclaimer in the documentation and/or other
   materials provided with the distribution.

3. Neither the name of Nordic Semiconductor ASA nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

4. This software, with or without modification, must only be used with a
   Nordic Semiconductor ASA integrated circuit.

5. Any software provided in binary form under this license must not be reverse
   engineered, decompiled, modified and/or disassembled.

THIS SOFTWARE IS PROVIDED BY NORDIC SEMICONDUCTOR ASA "AS IS" AND ANY EXPRESS
OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY, NONINFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL NORDIC SEMICONDUCTOR ASA OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
/* This file was generated by plugin '<%= PluginInfo.Name %>' (BDS version <%= PluginInfo.AppVersion %>) */

#include "service_if.h"
#include <stdint.h>

#define NRF_LOG_MODULE_NAME Bluetooth_IF
#include "nrf_log.h"
NRF_LOG_MODULE_REGISTER(); <%


var uniqueNames = _.uniq(_.pluck(Services, "ShortName"));
for(var i=0; i<uniqueNames.length; i++) { %>
#include "ble_<%= uniqueNames[i] %>.h" <%
}
%>

<%
if (enriched.jobsForUser != '') {
    print('/*\r\n' + enriched.jobsForUser + '*/\r\n');
}
%>

<%
_.each(Services, function (service) { %>
ble_<%= service.ShortName %>_t    m_<%= service.UniqueName %>; <%
}); %>
<%
_.each(Services, function (service) {
    _.each(service.Characteristics, function(characteristic) {
        _.each(characteristic.Fields, function(field) {
            if(field.FormatType() === "uint8_array") { %>
uint8_t m_<%= service.UniqueName %>_<%= characteristic.NormalizedName() %>_initial_value_<%= field.NormalizedName() %>_arr[1]; <%
            }
            else if(field.FormatType() === "regcertdatalist") { %>
uint8_t	m_<%= service.UniqueName %>_<%= characteristic.NormalizedName() %>_initial_value_<%= field.NormalizedName() %>_arr[1]; <%
            }
        });
    });
}); %>
<%
_.each(Services, function (service) { %>

/**@brief Function for handling the <%= service.Name %> events.
 *
 * @details This function will be called for all <%= service.Name %> events which are passed to
 *          the application.
 *
 * @param[in]   p_<%= service.NormalizedName() %>   <%= service.Name %> structure.
 * @param[in]   p_evt   Event received from the <%= service.Name %>.
 */
static void on_<%= service.UniqueName %>_evt(ble_<%= service.ShortName %>_t * p_<%= service.ShortName %>, ble_<%= service.ShortName %>_evt_t * p_evt)
{
    switch (p_evt->evt_type)
    { <%
        _.each(service.Characteristics, function(characteristic) {
            if (characteristic.isNotifySupported() || characteristic.isIndicateSupported()) { %>
        case BLE_<%= service.ShortName.toUpperCase() %>_<%= characteristic.NormalizedName().toUpperCase() %>_EVT_NOTIFICATION_ENABLED:
            NRF_LOG_INFO("<%= service.ShortName.toUpperCase() %>_<%= characteristic.NormalizedName().toUpperCase() %> evt NOTIFICATION_ENABLED. \r\n");
            break;
        case BLE_<%= service.ShortName.toUpperCase() %>_<%= characteristic.NormalizedName().toUpperCase() %>_EVT_NOTIFICATION_DISABLED:
            NRF_LOG_INFO("<%= service.ShortName.toUpperCase() %>_<%= characteristic.NormalizedName().toUpperCase() %> evt NOTIFICATION_DISABLED. \r\n");
            break;
        case BLE_<%= service.ShortName.toUpperCase() %>_<%= characteristic.NormalizedName().toUpperCase() %>_EVT_CCCD_WRITE:
            NRF_LOG_INFO("<%= service.ShortName.toUpperCase() %>_<%= characteristic.NormalizedName().toUpperCase() %> evt CCCD_WRITE. \r\n");
            break; <%
            }
            if (characteristic.isWriteSupported() || characteristic.isWriteWithoutResponseSupported()) { %>
        case BLE_<%= service.ShortName.toUpperCase() %>_<%= characteristic.NormalizedName().toUpperCase() %>_EVT_WRITE:
            NRF_LOG_INFO("<%= service.ShortName.toUpperCase() %>_<%= characteristic.NormalizedName().toUpperCase() %> evt WRITE. \r\n");
            break; <%
            }
        }); %>
        default:
            // No implementation needed.
            break;
    }
}
<%
}); %>

/**@brief Function for initializing the Services generated by Bluetooth Developer Studio.
 *
 *
 * @return      NRF_SUCCESS on successful initialization of services, otherwise an error code.
 */
uint32_t bluetooth_init(void)
{
    uint32_t    err_code; <%
    _.each(Services, function (service) { %>
    ble_<%= service.ShortName %>_init_t    <%= service.UniqueName %>_init; <%
    }); %>
    <%
    _.each(Services, function (service) { %>

    // Initialize <%= service.Name %>.
    memset(&<%= service.UniqueName %>_init, 0, sizeof(<%= service.UniqueName %>_init));

    <%= service.UniqueName %>_init.evt_handler = on_<%= service.UniqueName %>_evt; <%
        _.each(service.Characteristics, function(characteristic) {
            if (characteristic.isReadSupported() && !characteristic.isReadMandatory()) { %>
    <%= service.UniqueName %>_init.is_<%= characteristic.NormalizedName() %>_read_supported = true;<%
            }
            if (characteristic.isNotifySupported() && !characteristic.isNotifyMandatory()) { %>
    <%= service.UniqueName %>_init.is_<%= characteristic.NormalizedName()%>_notify_supported = true;<%
            }
            if (characteristic.isIndicateSupported() && !characteristic.isIndicateMandatory()) { %>
    <%= service.UniqueName %>_init.is_<%= characteristic.NormalizedName()%>_indicate_supported = true;<%
            }
            if (characteristic.isWriteSupported() && !characteristic.isWriteMandatory()) { %>
    <%= service.UniqueName %>_init.is_<%= characteristic.NormalizedName() %>_write_supported = true;<%
            }
            if (characteristic.isWriteWithoutResponseSupported() && !characteristic.isWriteWithoutResponseMandatory()) { %>
    <%= service.UniqueName %>_init.is_<%= characteristic.NormalizedName() %>_write_wo_resp_supported = true;<%
            }
            if (characteristic.isReliableWriteSupported() && !characteristic.isReliableWriteMandatory()) { %>
    <%= service.UniqueName %>_init.is_<%= characteristic.NormalizedName() %>_reliable_write_supported = true;<%
            }
            print("\r\n");
            enriched.showService = service;
            enriched.showCharacteristic = characteristic;
            enriched.showName = service.UniqueName + "_init.ble_" + service.ShortName + "_" + characteristic.NormalizedName() + "_initial_value";
            print(prettify(innerTemplates.CHAR_DEFAULTS(enriched), 1));
        }); %>

    err_code = ble_<%= service.ShortName %>_init(&m_<%= service.UniqueName %>, &<%= service.UniqueName %>_init);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } <%
    }); %>

    return NRF_SUCCESS;
}

/**@brief Function for handling the Application's BLE Stack events.
 *
 * @details Handles all events from the BLE stack of interest to all Bluetooth Developer Studio generated Services.
 *
 * @param[in]   p_ble_evt  Event received from the BLE stack.
 */
void bluetooth_on_ble_evt(ble_evt_t const * p_ble_evt)
{ <%
    _.each(Services, function (service) { %>
    ble_<%= service.ShortName %>_on_ble_evt(&m_<%= service.UniqueName %>, p_ble_evt); <%
    }); %>
}

